{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-c50
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/C50_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/C50/C50_{{ version }}.tar.gz
  sha256: af02d745ac1363a1d3df2d310fb4c90f2e5b52ca93a90254135aa46083d4c69f

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cubist >=0.2.3
    - r-partykit
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cubist >=0.2.3
    - r-partykit

test:
  commands:
    - $R -e "library('C50')"           # [not win]
    - "\"%R%\" -e \"library('C50')\""  # [win]

about:
  home: https://topepo.github.io/C5.0
  license: GPL-3
  summary: C5.0 decision trees and rule-based models for pattern recognition that extend the work of Quinlan (1993, ISBN:1-55860-238-0).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: C50
# Type: Package
# Title: C5.0 Decision Trees and Rule-Based Models
# Version: 0.1.3
# Authors@R: c( person("Max", "Kuhn", , "mxkuhn@gmail.com", c("aut", "cre")), person("Steve", "Weston", role = "ctb"), person("Mark", "Culp", role = "ctb"), person("Nathan", "Coulter", role = "ctb"), person("Ross", "Quinlan", role = "aut", comment = "Author of imported C code"), person("RuleQuest Research", role = "cph", comment = "Copyright holder of imported C code"), person("Rulequest Research Pty Ltd.", role = "cph", comment = "Copyright holder of imported C code"))
# Maintainer: Max Kuhn <mxkuhn@gmail.com>
# Description: C5.0 decision trees and rule-based models for pattern recognition that extend the work of Quinlan (1993, ISBN:1-55860-238-0).
# Imports: partykit, Cubist (>= 0.2.3)
# Depends: R (>= 2.10.0)
# Suggests: knitr, modeldata
# URL: https://topepo.github.io/C5.0
# BugReports: https://github.com/topepo/C5.0/issues
# License: GPL-3
# LazyLoad: yes
# RoxygenNote: 7.0.2.9000
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2020-01-10 17:47:27 UTC; max
# Author: Max Kuhn [aut, cre], Steve Weston [ctb], Mark Culp [ctb], Nathan Coulter [ctb], Ross Quinlan [aut] (Author of imported C code), RuleQuest Research [cph] (Copyright holder of imported C code), Rulequest Research Pty Ltd. [cph] (Copyright holder of imported C code)
# Repository: CRAN
# Date/Publication: 2020-01-13 10:00:02 UTC
