travis:
  secure:
    BINSTAR_TOKEN: kTYZiq/bbrv+KeKuld7TmZTHr9vBo3Jrk9SqhO4b913aKI8MJb6OluYIvNDEb0z1dGzqYC0HTiCMrrkvEE+8abBnUFSM+Q2LN1w2qPcUiK0WD2x1m/Fws8fAe/p9yfINuzeffXkrMFUjJ77H3uU633K/JrqkXy+DuLKZEwoyC0nOqqqBOQyNJgXS7N5F6UJEfZdYm0RGFqRaHu2pvaT++V3sHF6nILImphSKxhNSEl1QXvFyxoxEh7IhC4eBOD3JSrnwsSU0SXLKpN75n6x/DipUXZoVHiUVs925CQPmWIQ/MiMXSjaw8Hw9Hf68s4GgYsWjP9IqH1ngnzLODKJkuIZtDWH0HCaQkc/CRZotWAljOwORmtHHXrDwuVQ2SIet5jQJeIXLTbHmQgfyeEWUr8m3SIiViA/Fmon9nwkimYZtjM2PheeEl61TX4fNUtFt149J31+YILrICqI6StEduTPAvjjGz5NbnWdBtRqqiRiuCn6+Zal35T0tIzdMy/sQgn8tD1FJGu19qFiqJ8hAuAthtTNOhAeEtxvcE3zkTDqg4ytmf7KetkC9GYnZVJ7/7uhwuPLzO56BU42vjPIW6pJGPW/ztCE1/R0nHJjpsqXuSU9k6zJno443bUEHukWoVx22f6eWsuN05H1bqr2HJAA5UmpMOqSnM4g94Rf4igw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
