travis:
  secure:
    BINSTAR_TOKEN: mCOGnf0hJXGbG5nuPdqr7JvA/EjAo1eArwKL/RWIugsIt431vMx5y5yOx6HEi9fgS2Nbl/SkPPSSQn0zUkIPteTCWPYODUcz0+kddqjMz8PVTVV5nNhO1KNeI8fGN/S+Rq68+poFWxlGPztC7/j8TljYnW0nmuCQMTJHFIVoc1IImJQfwg/eb6tC2NYIA9f3kmxgHTFrCpf1SgDBjtIjW8yK64s/kSG8No5ZPzoexaBZWBR73dHPAkvLC9UPGlup2gnvdjRhtNqnQ9kb6YgSDfvEGH93b9zKMx2wZSQcFMk7fQjsfTtMLCvVgCjo9ARZw+4G1bHGGtkvotPbyRuVyiVmLtgsR85vqBEklf1UFRLp1T+vMDp679MiaM0m39i0moHMnUAN77CiaL0+8KV8agccASl+CUkfg6zZLEVe9lktvUIrx/6+2LRLCXqmp0/nN/rUw/gtUcotCQc0tWsMzr3WfY5trNqvJcWnpUhZPjpIoUIn356OC8QFmzV24yyqbVp1+a1MYOn+feeYrqyMALM1MQQ3wEie40uUtlRiai9R13xGGwf43eJPB0R1nuZTuutj8r9edxxxoI+oGLlsvneubK45Nra/Jxfk5BQcN7kJQGipt5Rz3eJQVig7TPuCOsM9hN1PoBonkcA76dK/7dvTa94mPDO7aFkCnuCCuYw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
