appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Cz4UhUIhy6L2L+FgCR/TSfgoa3yq9lXXkQK0DZOls0K9vJ0cB6DRp2dhNpbipFPBFu6ELTtDURaZPOhXHaRTqz0h/Rp4eICwLq8RNarZbbojaAb6CExwDjulQ2qRT2MZH+ifvHAmuwsz2xNVizxcdduLt8xqGK1A64SKyD83IPw87uVtnLaTisFMhklRVXrvv+EKxYiGAFS4CuZgzEFxxN3alJ0lIYqxESMpqsHicVXi+XOONBtWD0/tNg+PW0ziGVUogEvvPxxHPXH86Qv9RqJnj5ihhT2TZP03wrdOrHFFqwQKlyZnsl6mKRpS1U2rXvk1B02YIsurTEsjbSbzABmWwov3m+Zal6i8gOaKD3jJEAIy9VelVG8i+C/ABQZwk0rIM3vkrZRsIPo7sZFSTCajbDAqjEd6Sc7wQE/mE1U4Eu4krbunmcVEb9g4lsBxn/erQX7SSs1ORzaUn6j/ANfKNMFjC+Z6ijf9p8D0yro1d7HzsT1fa3LSpFOWtuf9A8www7CoNl8Z2r/123MmDJtUOkGYtMUjtzceehLmKPCJFGvEzx1nlVTWVNP93wIjp86atQAtYozcrBMRztDgSIVpE7Dire3KygDP6PqNKfSU5YJ1TGqHNRikGmW1LYQKmvUrAQxbMm3iDvtLSmhtnub3e3rNaUFCbgwpWNf0Cig=
conda_forge_output_validation: true
