travis:
  secure:
    BINSTAR_TOKEN: QPf3ueAjLS0IuJC3FAMRySJlxsDoDvYq5ypYFOcmlmbdOFHQ75L4m+t3xSMpzOLcieTzpj8qyK65T+I8YblZJlrUy43+Du4fpMnswQLYn39luJLFjTiei164bfMkBQpTSkCCubavNAs1QQPAqia10sFleeSG7eUyfGRWWJJVhPHarhe1VfvJTOdEDj3y50rc+XNuLaU8AIcjt+Ja7nu+gntEa8nBzTbStzOu/k9l+C0OReo6bKT9mS/QgFVzsWs8kNi6pX3HipT9dq28M6JtZgBeHskCvJ1cYQxSX9+BiMOO89kBWEA7nfq1ANLTlTCkPewgl45wM7yh/BPVD5u4v2q+/tP04DnSTlnYIrh6zRIbUgYgEozry50EMmrt7AFulSXEB6D3WPSELrKf/wv5sw8k4fUuTBsbIGZWoMgFo+IhKyvzjoLuAAioxi8A6zb7nep7vzQ2RH3L/FJfOGat8cSewaXbLwC2qtE9avdsADSQ3sGWhCQbwCC7THF0ayTQFFXDnzFK7Ki0sEU/L7pKEU6H2SsFty+jw5Ed+++MzEGVcWxo2ZPkDW7hMn2O6SCClAEQ5uU0kKa7Gm1/izdoufshMZBYXmxmcJMuI8zE4GHPGXzT36DJ7H7dkbnqcKbK05v5sWhWftFiYzdpmQny1v19WC3rL6UfwtnokIG/Deg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
